set-option -g prefix C-b

bind-key n last-window
bind-key m send-prefix
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g default-terminal "tmux-256color"
set -ga terminal-features ",xterm-ghostty:RGB"

set -g status-position bottom
set -g status-style 'fg=#829181,bg=#e5dfc5'
set -g status-left ''
set -g status-right '#[fg=#f3ead3,bg=#939f91,bold] %d/%m #[fg=#f3ead3,bg=#93b259,bold] %H:%M:%S '
set -g status-right-length 50
set -g status-left-length 20

setw -g window-status-current-style 'fg=#8da101,bg=#ddd8be,bold'
setw -g window-status-current-format ' #I#[fg=#939f91]:#[fg=#5c6a72]#W#[fg=#35a77c]#F '

setw -g window-status-style 'fg=#939f91'
setw -g window-status-format ' #I#[fg=#a6b0a0]:#[fg=#829181]#W#[fg=#a6b0a0]#F '

setw -g window-status-bell-style 'fg=#f3ead3,bg=#f85552,bold'

set-window-option -g mode-keys vi
set -g status-keys vi
setw -g mouse on
