#!/usr/bin/env bash

EXECUTABLE="+0111"
script_dir=$(cd $(dirname "${BASH_SOURCE[0]}") && pwd)
filter=""
dry="0"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  echo ""
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "executing $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

cd $script_dir
scripts=$(find ./runs -maxdepth 1 -mindepth 1 -perm "$EXECUTABLE" -type f)

for script in $scripts; do
  if echo "$script" | grep -qv "$filter"; then
    log "filtering $script"
    continue
  fi
  execute ./$script
done
