#!/usr/bin/env bash

dry="0"

while [[ $# -gt 0 ]]; do
  if [[ $1 == "--dry" ]]; then
    dry="1"
  else
    filter="$1"
  fi
  shift
done

log() {
  if [[ $dry == "1" ]]; then
    echo "[DRY RUN]: $@"
  else
    echo "$@"
  fi
}

execute() {
  log "executing $@"
  if [[ $dry == "1" ]]; then
    return
  fi
  "$@"
}

copy_dir() {
  from=$1
  to=$2

  pushd $from > /dev/null
  dirs=$(find . -mindepth 1 -maxdepth 1 -type d)
  for dir in $dirs; do
    execute rm -rf $to/$dir
    execute cp -r $dir $to/$dir
  done
  popd > /dev/null
}

copy_file() {
  from=$1
  to=$2
  name=$(basename $from)

  execute rm $to/$name
  execute cp $from $to/$name
}

append_or_copy_file() {
  from=$1
  to=$2
  name=$(basename $from)

  target=$to/$name
  start=$(head -n 1 "$from")
  end=$(tail -n 1 "$from")
  log $start
  log $end

  if [ -f "$target" ] && rg -Fxq "$start" "$target" && rg -Fxq "$end" "$target"; then
    tmp=$(mktemp)
    sed "/^$start$/,/^$end$/d" "$target" > "$tmp"
    {
      echo "$start"
      tail -n +2 "$from" | head -n -1
      echo "$end"
    } >> "$tmp"
    execute mv "$tmp" "$target"
  else
    execute cp $from $target
  fi
}

copy_dir .config ~/.config
copy_file .tmux.conf ~
append_or_copy_file .zshrc ~
